Import('env')

test_env = env.Clone()
test_env.Append(
  CPPPATH = [
    "#/test"
  ]
)

tut_tests = [
  "testUtils.cpp",
  "RLMachine_TUT.cpp",
  "Module_Jmp_TUT.cpp",
  "Module_Str_TUT.cpp",
  "Module_Mem_TUT.cpp",
  "Module_Sys_TUT.cpp",
  "ExpressionTest_TUT.cpp",
  "TextSystem_TUT.cpp",
  "Gameexe_TUT.cpp",
  "LazyArray_TUT.cpp",
  "GraphicsObject_TUT.cpp",
  "Effect_TUT.cpp",
]

nullsystem_files = [
  "NullSystem/NullSystem.cpp",
  "NullSystem/NullEventSystem.cpp",
  "NullSystem/NullTextSystem.cpp",
  "NullSystem/NullTextWindow.cpp",
  "NullSystem/NullGraphicsSystem.cpp",
  "NullSystem/NullSoundSystem.cpp",
  "NullSystem/NullSurface.cpp",
  "NullSystem/MockLog.cpp"
]

scriptmachine_files = [
  "ScriptMachine/ScriptWorld.cpp",
  "ScriptMachine/ScriptMachine.cpp",
  "ScriptMachine/luabind_Machine.cpp",
  "ScriptMachine/luabind_System.cpp",
  "ScriptMachine/luabind_EventSystem.cpp",
  "ScriptMachine/luabind_GraphicsSystem.cpp",
  "ScriptMachine/luabind_GraphicsObject.cpp",
  "ScriptMachine/luabind_utility.cpp",
]

test_env.Program('rlvm-tests', ["rlvmTest.cpp", nullsystem_files,
                                tut_tests, 'librlvm.a'])

