# Main scons file

import shutil
import sys

Import('env')

########################################################## [ Root environment ]
root_env = env.Clone()
root_env.Append(
  CPPDEFINES = [
    "CASE_SENSITIVE_FILESYSTEM",
    "_THREAD_SAFE"
  ],

  CXXFLAGS = [
    "--ansi",
    "-Wall",
    "-Wno-sign-compare",
    "-Wno-narrowing",
    "-std=c++11"
  ]
)

# if root_env['PLATFORM'] == 'darwin':
#   root_env.Append(FRAMEWORKS=["OpenGL"])
# else:

root_env.ParseConfig("sdl-config --libs")

#########################################################################

# All the PNG files taken from The Mana World that we want to compile in
guichan_resources = [
  "src/platforms/gcn/button_disabled.png",
  "src/platforms/gcn/buttonhi.png",
  "src/platforms/gcn/button.png",
  "src/platforms/gcn/buttonpress.png",
  "src/platforms/gcn/deepbox.png",
  "src/platforms/gcn/hscroll_left_default.png",
  "src/platforms/gcn/hscroll_left_pressed.png",
  "src/platforms/gcn/hscroll_right_default.png",
  "src/platforms/gcn/hscroll_right_pressed.png",
  "src/platforms/gcn/vscroll_down_default.png",
  "src/platforms/gcn/vscroll_down_pressed.png",
  "src/platforms/gcn/vscroll_grey.png",
  "src/platforms/gcn/vscroll_up_default.png",
  "src/platforms/gcn/vscroll_up_pressed.png"
]

# Build the resource compiler and then use it to make the inline header file.
root_env.Program('wxInclude', ['vendor/wxInclude.cpp'])
root_env.Command('$BUILD_DIR/resource_header.h',
                 ['$BUILD_DIR/wxInclude', guichan_resources],
                 ["$SOURCE --silent --wxnone --output-file=$TARGET " +
                  " ".join(guichan_resources)])

# We'll need to be able to see the autogenerated header:
root_env.Append(
  CPPPATH = ["$BUILD_DIR"]
)

#########################################################################

librlvm_files = [
  "src/base/notification_details.cc",
  "src/base/notification_registrar.cc",
  "src/base/notification_service.cc",
  "src/base/notification_source.cc",
  "src/effects/blind_effect.cc",
  "src/effects/effect.cc",
  "src/effects/effect_factory.cc",
  "src/effects/fade_effect.cc",
  "src/effects/scroll_on_scroll_off.cc",
  "src/effects/wipe_effect.cc",
  "src/encodings/codepage.cc",
  "src/encodings/cp932.cc",
  "src/encodings/cp936.cc",
  "src/encodings/cp949.cc",
  "src/encodings/han2zen.cc",
  "src/encodings/western.cc",
  "src/libreallive/archive.cc",
  "src/libreallive/bytecode.cc",
  "src/libreallive/compression.cc",
  "src/libreallive/expression.cc",
  "src/libreallive/filemap.cc",
  "src/libreallive/gameexe.cc",
  "src/libreallive/intmemref.cc",
  "src/libreallive/scenario.cc",
  "src/long_operations/button_object_select_long_operation.cc",
  "src/long_operations/load_game_long_operation.cc",
  "src/long_operations/pause_long_operation.cc",
  "src/long_operations/select_long_operation.cc",
  "src/long_operations/textout_long_operation.cc",
  "src/long_operations/wait_long_operation.cc",
  "src/long_operations/zoom_long_operation.cc",
  "src/machine/dump_scenario.cc",
  "src/machine/game_hacks.cc",
  "src/machine/general_operations.cc",
  "src/machine/long_operation.cc",
  "src/machine/mapped_rlmodule.cc",
  "src/machine/memory.cc",
  "src/machine/memory_intmem.cc",
  "src/machine/opcode_log.cc",
  "src/machine/rlmachine.cc",
  "src/machine/rlmodule.cc",
  "src/machine/rloperation.cc",
  "src/machine/reallive_dll.cc",
  "src/machine/save_game_header.cc",
  "src/machine/serialization_global.cc",
  "src/machine/serialization_local.cc",
  "src/machine/stack_frame.cc",
  "src/machine/reference.cc",
  "src/modules/object_mutator_operations.cc",
  "src/modules/module_bgm.cc",
  "src/modules/module_bgr.cc",
  "src/modules/module_dll.cc",
  "src/modules/module_debug.cc",
  "src/modules/module_event_loop.cc",
  "src/modules/module_g00.cc",
  "src/modules/module_gan.cc",
  "src/modules/module_grp.cc",
  "src/modules/module_jmp.cc",
  "src/modules/module_koe.cc",
  "src/modules/module_mem.cc",
  "src/modules/module_mov.cc",
  "src/modules/module_msg.cc",
  "src/modules/module_obj.cc",
  "src/modules/module_obj_creation.cc",
  "src/modules/module_obj_fg_bg.cc",
  "src/modules/module_obj_management.cc",
  "src/modules/module_obj_getters.cc",
  "src/modules/module_os.cc",
  "src/modules/module_pcm.cc",
  "src/modules/module_refresh.cc",
  "src/modules/module_scr.cc",
  "src/modules/module_se.cc",
  "src/modules/module_sel.cc",
  "src/modules/module_shk.cc",
  "src/modules/module_shl.cc",
  "src/modules/module_str.cc",
  "src/modules/module_sys.cc",
  "src/modules/module_sys_date.cc",
  "src/modules/module_sys_frame.cc",
  "src/modules/module_sys_name.cc",
  "src/modules/module_sys_save.cc",
  "src/modules/module_sys_syscom.cc",
  "src/modules/module_sys_timer.cc",
  "src/modules/module_sys_wait.cc",
  "src/modules/module_sys_index_series.cc",
  "src/modules/module_sys_timetable2.cc",
  "src/modules/modules.cc",
  "src/Systems/Base/AnmGraphicsObjectData.cpp",
  "src/Systems/Base/CGMTable.cpp",
  "src/Systems/Base/Colour.cpp",
  "src/Systems/Base/ColourFilterObjectData.cpp",
  "src/Systems/Base/DigitsGraphicsObject.cpp",
  "src/Systems/Base/DriftGraphicsObject.cpp",
  "src/Systems/Base/EventListener.cpp",
  "src/Systems/Base/EventSystem.cpp",
  "src/Systems/Base/FrameCounter.cpp",
  "src/Systems/Base/GanGraphicsObjectData.cpp",
  "src/Systems/Base/GraphicsObject.cpp",
  "src/Systems/Base/GraphicsObjectData.cpp",
  "src/Systems/Base/GraphicsObjectOfFile.cpp",
  "src/Systems/Base/GraphicsStackFrame.cpp",
  "src/Systems/Base/GraphicsSystem.cpp",
  "src/Systems/Base/GraphicsTextObject.cpp",
  "src/Systems/Base/HIKRenderer.cpp",
  "src/Systems/Base/HIKScript.cpp",
  "src/Systems/Base/KOEPACVoiceArchive.cpp",
  "src/Systems/Base/LittleBustersEF00DLL.cpp",
  "src/Systems/Base/LittleBustersPT00DLL.cpp",
  "src/Systems/Base/MouseCursor.cpp",
  "src/Systems/Base/NWKVoiceArchive.cpp",
  "src/Systems/Base/ObjectMutator.cpp",
  "src/Systems/Base/ObjectSettings.cpp",
  "src/Systems/Base/OVKVoiceArchive.cpp",
  "src/Systems/Base/OVKVoiceSample.cpp",
  "src/Systems/Base/ParentGraphicsObjectData.cpp",
  "src/Systems/Base/Platform.cpp",
  "src/Systems/Base/RLTimer.cpp",
  "src/Systems/Base/RlBabelDLL.cpp",
  "src/Systems/Base/Rect.cpp",
  "src/Systems/Base/SelectionElement.cpp",
  "src/Systems/Base/SoundSystem.cpp",
  "src/Systems/Base/Surface.cpp",
  "src/Systems/Base/System.cpp",
  "src/Systems/Base/SystemError.cpp",
  "src/Systems/Base/TextKeyCursor.cpp",
  "src/Systems/Base/TextPage.cpp",
  "src/Systems/Base/TextSystem.cpp",
  "src/Systems/Base/TextWaku.cpp",
  "src/Systems/Base/TextWakuNormal.cpp",
  "src/Systems/Base/TextWakuType4.cpp",
  "src/Systems/Base/TextWindow.cpp",
  "src/Systems/Base/TextWindowButton.cpp",
  "src/Systems/Base/TomoyoAfterDT00DLL.cpp",
  "src/Systems/Base/ToneCurve.cpp",
  "src/Systems/Base/VoiceArchive.cpp",
  "src/Systems/Base/VoiceCache.cpp",
  "src/Utilities/Exception.cpp",
  "src/Utilities/File.cpp",
  "src/Utilities/Graphics.cpp",
  "src/Utilities/StringUtilities.cpp",
  "src/Utilities/dateUtil.cpp",
  "src/Utilities/findFontFile.cpp",
  "src/Utilities/math_util.cpp",
  "vendor/xclannad/endian.cpp",
  "vendor/xclannad/file.cc",
  "vendor/xclannad/koedec_ogg.cc",
  "vendor/xclannad/nwatowav.cc",
  "vendor/xclannad/wavfile.cc"
]

root_env.StaticLibrary('rlvm', librlvm_files)

libsystemsdl_files = [
  "src/Systems/SDL/SDLAudioLocker.cpp",
  "src/Systems/SDL/SDLColourFilter.cpp",
  "src/Systems/SDL/SDLEventSystem.cpp",
  "src/Systems/SDL/SDLGraphicsSystem.cpp",
  "src/Systems/SDL/SDLMusic.cpp",
  "src/Systems/SDL/SDLRenderToTextureSurface.cpp",
  "src/Systems/SDL/SDLSoundChunk.cpp",
  "src/Systems/SDL/SDLSoundSystem.cpp",
  "src/Systems/SDL/SDLSurface.cpp",
  "src/Systems/SDL/SDLSystem.cpp",
  "src/Systems/SDL/SDLTextSystem.cpp",
  "src/Systems/SDL/SDLTextWindow.cpp",
  "src/Systems/SDL/SDLUtils.cpp",
  "src/Systems/SDL/Shaders.cpp",
  "src/Systems/SDL/Texture.cpp",
  "vendor/pygame/alphablit.cc"
]

root_env.StaticLibrary('system_sdl', libsystemsdl_files)

guichan_platform = [
  "src/platforms/gcn/gcn_button.cc",
  "src/platforms/gcn/gcn_graphics.cc",
  "src/platforms/gcn/gcn_info_window.cc",
  "src/platforms/gcn/gcn_menu.cc",
  "src/platforms/gcn/gcn_platform.cc",
  "src/platforms/gcn/gcn_save_load_window.cc",
  "src/platforms/gcn/gcn_scroll_area.cc",
  "src/platforms/gcn/gcn_true_type_font.cc",
  "src/platforms/gcn/gcn_utils.cc",
  "src/platforms/gcn/gcn_window.cc",
]

root_env.StaticLibrary('guichan_platform', guichan_platform)
