.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH RLVM 6 "Sept 2014" "rlvm"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
rlvm \- RealLive interpreter clone
.SH SYNOPSIS
.B rlvm
[\fIOPTION\fR]... <path to directory containing a Gameexe.ini file>
.SH DESCRIPTION
.PP
rlvm is a Free Software reimplementation of the VisualArt's KK's
RealLive interpreter. It is meant to provide Linux and Apple users
with a compatible, portable interpreter to play VisualArts games,
specifically those released by Key.
.TP 
\fB\-\-font\fR
Specifies the path to a TrueType font to use instead of trying to autodetect the font
.SH SUPPORTED GAMES
.sp 1
Currently, rlvm can run the following games:
.IP \[bu] 2
Kanon
.IP \[bu]
Kanon (With NDT's English patch)
.IP \[bu]
AIR
.IP \[bu]
CLANNAD / CLANNAD Full Voice Edition
.IP \[bu]
Planetarian
.IP \[bu]
Planetarian (US Edition)
.IP \[bu]
Tomoyo After
.IP \[bu]
Little Busters
.IP \[bu]
Kud Wafter
.TP 0
In addition, there is partial support for:
.IP \[bu] 2
Princess Bride
.IP \[bu]
Princess Brave
.IP \[bu]
ALMA ~zutto soba ni~
.IP \[bu]
SNOW
.IP \[bu]
Some of the game demos from the Kinetic Novel website.
.SH FILES
.I ~/.rlvm/
.RS
All rlvm save files are kept in this directory.
.SH BUGS?
While rlvm is generally stable, emulation of the RealLive virtual machine is
incomplete.
.SH NOT A BUG
English patches that were not compiled with rlBabel will not line break
correctly. You can check if your patch is compiled with rlBabel and the text
encoding is set to "Western" by hitting [F1] at any time.
.SH AUTHOR
rlvm was written by Elliot Glaysher, with the help of Haeleth. Special thanks
to Jagarl for licensing all his RealLive file reading code under liberal
licenses, and for doing the first reverse engineering of the RealLive
system. Windows port and bug fixes made possible by Rasqual Twilight.
.PP
This manual page was written by Elliot Glaysher <glaysher@umich.edu>.
